name: Build and publish
on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  GO_VERSION: "1.22"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true

      - name: Pull common linter configs
        run: wget -O .golangci.yml https://raw.githubusercontent.com/JenswBE/setup/main/programming_configs/golang/.golangci.yml

      - name: Lint service
        uses: golangci/golangci-lint-action@v5

      - name: Generate website
        run: go run .

      - name: Publish to VPS
        run: |
          touch ssh_key
          chmod 600 ssh_key
          echo '${{ secrets.SSH_KEY }}' > ssh_key
          rsync --verbose --archive --delete --rsh='ssh -p ${{ vars.SSH_PORT }} -i ssh_key' output/ ${{ vars.SSH_USER }}@${{ vars.SSH_HOST }}:/
